import {Link} from 'react-router-dom';
import LandingLayout from '../components/landing/LandingLayout';
export default function PrivacyPage() {
  return <LandingLayout><article className="mx-auto max-w-3xl px-6 py-14"><p className="text-xs font-semibold uppercase tracking-widest text-indigo-700">Data transparency</p><h1 className="mt-3 text-4xl font-bold tracking-tight">Your data in Prep Pilot</h1><p className="mt-5 leading-7 text-gray-600">This page explains what the app stores and how its preparation features use your information.</p>
    <div className="mt-10 space-y-8 text-sm leading-7 text-gray-700">
      <section><h2 className="text-lg font-semibold text-gray-900">What is saved</h2><p className="mt-2">Your account email and a password hash; uploaded resume files and extracted text; job descriptions and corrected skills; generated questions and guidance; saved answer drafts, bookmarks, submitted attempts, and feedback. A login token is stored in your browser to keep you signed in.</p></section>
      <section><h2 className="text-lg font-semibold text-gray-900">When information goes to AI</h2><p className="mt-2">Generating questions or guidance sends relevant resume and job-description text to OpenAI. Requesting feedback sends your submitted answer, the question, resume context, and a previous attempt when available. Saving a draft alone does not request AI feedback.</p><p className="mt-2">Remove contact details and any confidential employer or client information you do not want included before uploading or submitting text. AI guidance can be wrong; verify personal claims and technical advice.</p></section>
      <section><h2 className="text-lg font-semibold text-gray-900">Where the app runs</h2><p className="mt-2">The frontend is hosted on Vercel, the API on Render, and application records in PostgreSQL. These hosting services and the AI provider process the information needed to provide the service. Their own storage and retention policies also apply.</p></section>
      <section><h2 className="text-lg font-semibold text-gray-900">Removing saved preparation</h2><p className="mt-2">From your dashboard, delete an interview session to remove its questions, guidance, drafts, bookmarks, attempts, and feedback from the active application database. To remove a resume or job description, first delete sessions that reference it, then choose Remove in Practice materials. Removal is permanent in the app.</p><p className="mt-2">Saved preparation remains available until you remove it. Removing data from the app does not by itself guarantee immediate removal from service-provider backups or logs.</p></section>
      <section><h2 className="text-lg font-semibold text-gray-900">Password recovery</h2><p className="mt-2">When recovery email is configured, the delivery provider receives your email address and a single-use reset link. Reset links expire after 15 minutes. The app stores a hash of the reset token and invalidates existing login sessions when your password changes.</p></section>
    </div><Link to="/dashboard" className="mt-10 inline-block rounded-lg bg-indigo-700 px-5 py-3 text-sm font-semibold text-white">Manage your preparation →</Link>
  </article></LandingLayout>;
}
